// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKK580z6we7R8U1274OHSwA5chkB-nFQI',
    appId: '1:266561304092:web:89f90eac1863be3a60d1d9',
    messagingSenderId: '266561304092',
    projectId: 'dog-did',
    authDomain: 'dog-did.firebaseapp.com',
    databaseURL: 'https://dog-did-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dog-did.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-Vf0mdurXOgSXLx4duv0q2Sqcoz9Xz4',
    appId: '1:266561304092:android:b1c794676888bdef60d1d9',
    messagingSenderId: '266561304092',
    projectId: 'dog-did',
    databaseURL: 'https://dog-did-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dog-did.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcuNAmuq6tZhUrv9eGdxRB0hcEvipmRSY',
    appId: '1:266561304092:ios:6e6c33456f9dfb6160d1d9',
    messagingSenderId: '266561304092',
    projectId: 'dog-did',
    databaseURL: 'https://dog-did-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dog-did.appspot.com',
    iosClientId: '266561304092-kt7v6gmb8cojt9fus253hos99ibg03fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogDid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcuNAmuq6tZhUrv9eGdxRB0hcEvipmRSY',
    appId: '1:266561304092:ios:6e6c33456f9dfb6160d1d9',
    messagingSenderId: '266561304092',
    projectId: 'dog-did',
    databaseURL: 'https://dog-did-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dog-did.appspot.com',
    iosClientId: '266561304092-kt7v6gmb8cojt9fus253hos99ibg03fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogDid',
  );
}
